# dnsmasq.conf - Konfigurasi DHCP Server
# File ini juga di-generate otomatis oleh run.sh

interface=wlan0mon
dhcp-range=10.0.0.2,10.0.0.100,12h
dhcp-option=3,10.0.0.1
dhcp-option=6,10.0.0.1
no-resolv
port=0
log-queries

# Opsional: tambahkan domain
# domain=wifi.local